import org.junit.Test;

import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

/**
 * Created by xinyu.jiang on 2015/10/12.
 */
public class test {

    @Test
    public void test() {
        String json = "{\n" + "  \"R448\" : {\n" + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n"
                + "    \"ML7C2CH/A\" : \"ALL\",\n" + "    \"ML6H2CH/A\" : \"NONE\",\n"
                + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n" + "      \"zh_CN\" : {\n"
                + "        \"timeslotTime\" : \"下午 12:30\",\n" + "        \"contractTimeslotTime\" : \"下午 12:30\"\n"
                + "      }\n" + "    },\n" + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R534\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"ALL\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"ALL\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R479\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 1:00\",\n"
                + "        \"contractTimeslotTime\" : \"下午 1:00\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"ALL\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R502\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 1:00\",\n"
                + "        \"contractTimeslotTime\" : \"下午 1:00\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"ALL\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"ALL\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n" + "    \"ML6L2CH/A\" : \"ALL\",\n"
                + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R359\" : {\n" + "    \"ML7L2CH/A\" : \"ALL\",\n"
                + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R532\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R389\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R401\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R643\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R574\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R476\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"ALL\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"ALL\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n" + "    \"ML6L2CH/A\" : \"ALL\",\n"
                + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R388\" : {\n" + "    \"ML7L2CH/A\" : \"ALL\",\n"
                + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n"
                + "  \"isToday\" : true,\n" + "  \"R637\" : {\n" + "    \"ML7L2CH/A\" : \"ALL\",\n"
                + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R572\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"ALL\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R484\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"ALL\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R573\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"ALL\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n" + "    \"ML6L2CH/A\" : \"ALL\",\n"
                + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R320\" : {\n" + "    \"ML7L2CH/A\" : \"ALL\",\n"
                + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 1:00\",\n"
                + "        \"contractTimeslotTime\" : \"下午 1:00\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"R471\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"zh_CN\" : {\n"
                + "    \"launchDate\" : \"9月25日星期五\"\n" + "  },\n" + "  \"R480\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"ALL\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"ALL\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n" + "    \"ML6L2CH/A\" : \"ALL\",\n"
                + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  },\n" + "  \"updated\" : 1444622736108,\n" + "  \"R390\" : {\n"
                + "    \"ML7L2CH/A\" : \"ALL\",\n" + "    \"ML7F2CH/A\" : \"ALL\",\n" + "    \"ML7C2CH/A\" : \"ALL\",\n"
                + "    \"ML6H2CH/A\" : \"NONE\",\n" + "    \"ML6E2CH/A\" : \"NONE\",\n" + "    \"timeSlot\" : {\n"
                + "      \"zh_CN\" : {\n" + "        \"timeslotTime\" : \"下午 12:30\",\n"
                + "        \"contractTimeslotTime\" : \"下午 12:30\"\n" + "      }\n" + "    },\n"
                + "    \"ML6N2CH/A\" : \"NONE\",\n" + "    \"ML6K2CH/A\" : \"NONE\",\n"
                + "    \"ML6J2CH/A\" : \"NONE\",\n" + "    \"ML6D2CH/A\" : \"ALL\",\n"
                + "    \"ML6A2CH/A\" : \"ALL\",\n" + "    \"ML7K2CH/A\" : \"NONE\",\n"
                + "    \"ML6M2CH/A\" : \"NONE\",\n" + "    \"ML7H2CH/A\" : \"ALL\",\n"
                + "    \"ML6G2CH/A\" : \"NONE\",\n" + "    \"ML7E2CH/A\" : \"ALL\",\n"
                + "    \"ML6F2CH/A\" : \"NONE\",\n" + "    \"ML6C2CH/A\" : \"ALL\",\n"
                + "    \"ML7N2CH/A\" : \"ALL\",\n" + "    \"ML7D2CH/A\" : \"ALL\",\n" + "    \"ML7G2CH/A\" : \"ALL\",\n"
                + "    \"ML7P2CH/A\" : \"ALL\",\n" + "    \"ML7J2CH/A\" : \"ALL\",\n"
                + "    \"ML6L2CH/A\" : \"NONE\",\n" + "    \"ML7M2CH/A\" : \"ALL\"\n" + "  }\n" + "}";
        JsonParser jsonParser = new JsonParser();
        JsonElement jsonElement = jsonParser.parse(json);
        JsonObject asJsonObject = jsonElement.getAsJsonObject();
        asJsonObject.remove("isToday");
        asJsonObject.remove("zh_CN");
        asJsonObject.remove("updated");
        asJsonObject.get
        JsonArray asJsonArray = asJsonObject.getAsJsonArray();
    }
}
